### ISSUE TITLE
Invalid call of undeclared identifier 'texture2DRect'

### ISSUE THREAD

**Issue by cansik** [Syphon/Processing#27] opened 2015-12-02 08:15 UTC
When I try to run this simple sketch with **Processing 3.0.1**, I always get this error message when trying to get the image. It doesn't matter if I use `getGraphics` or `getImage`.

#### Sketch
```java
import codeanticode.syphon.SyphonClient;

SyphonClient client;
PGraphics img;

void setup()
{
  size(500, 500, P3D);
  client = new SyphonClient(this, "Simple Server");
}

void draw()
{
  if(client.active())
  {
    img = client.getGraphics(img);
    image(img, 0, 0, width, height);
  }
}
```

#### Error Message
```java
Syphon 2.0-RC2 by Andres Colubri http://andrescolubri.net/
2015-12-02 09:09:21.021 java[5970:532404] SYPHON DEBUG: SyphonClientConnectionManager: Registering for info updates
OpenGL error 1282 at top beginDraw(): invalid operation
Could not compile shader 35632:
ERROR: 0:11: Invalid call of undeclared identifier 'texture2DRect'
```

Am I doing something wrong or is it a bug?

**Comment by bangnoise** [comment] 2015-12-02 12:08
Unfortunately there's no core-profile support yet, see #25 

    void settings() {
        // ...
        PGJOL.profile = 1;
    }

**Comment by bangnoise** [comment] 2015-12-02 12:09
closing as dup #25

**Closed by bangnoise** 2015-12-02 12:09 UTC

**Comment by neilcsmith-net** [comment] 2017-01-12 17:20
Just out of interest, the cause of this particular error is a bug in Processing processing/processing#4810  I'm sure that isn't the only issue with core-profile support :smile: Although I had read something that would suggest a client might work?

**Comment by GSAixd** [comment] 2017-10-25 14:03
FWIW - my students were perplexed by why the suggested line above by bangnoise is wrong. There is a typo, and it should read:
```
void settings() {
    // ...
    PJOGL.profile = 1;
}
```
Hope this helps others.

**Comment by bangnoise** [comment] 2017-10-25 14:07
Core Profile support is here now - that line is no longer required. Update/install the Syphon library from the within Processing using the Contribution Manager (Sketch > Import Library... > Add Library...).

**Comment by GSAixd** [comment] 2017-10-25 20:14
Ah ok. Great - thanks.
